routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () { return view('welcome'); })->name('welcome');

//Ruta para usuarios y administroador para EventController@index (Calendario)
Route::get('/home', 'EventController@index')->name('home');

//Rutas Administrador
Route::namespace('Admin')->prefix('admin')->middleware(['auth', 'auth.admin'])->name('admin.')->group(function(){
    //Ruta para el Admin\ActividadesController
    Route::resource('/actividades', 'ActividadesController');

    //Ruta para el Admin\UserController
    Route::resource('/users', 'UserController');

    //Ruta para el Admin\ReservasController
    Route::resource('/reservas', 'ReservasController');

    //Ruta para crear el PDF como Administrador
    Route::get('generate-pdf/{id}','ActividadesController@generatePDF')->name('generarPDF');
});

//Rutas Usuarios
Route::namespace('User')->prefix('user')->middleware(['auth', 'auth.user'])->name('user.')->group(function(){
    //Ruta para crear una reserva.
    Route::get('/actividades/reservar/{id}', 'ReservasController@crear');

    //Ruta para el User\ActividadesController
    Route::resource('/actividades', 'ActividadesController');
    //Ruta para el User\ReservasController
    Route::resource('/reservas', 'ReservasController');

});

//Rutas Moderador
Route::namespace('Mod')->prefix('mod')->middleware(['auth', 'auth.mod'])->name('mod.')->group(function(){
    //Ruta para crear una reserva.
    Route::get('/actividades/ver/{id}', 'ActividadesController@ver');

    //Ruta para el Admin\ActividadesController
    Route::resource('/actividades', 'ActividadesController');

    //Ruta para el Admin\ReservasController
    Route::resource('/reservas', 'ReservasController');

    //Ruta para crer el PDF como Moderador
    Route::get('generate-pdf/{id}','ActividadesController@generatePDF')->name('generarPDF');
});

//Rutas para el follow de los usuarios
Route::get('users', 'User\UsuariosController@users')->name('users');
Route::get('user/{id}', 'User\UsuariosController@user')->name('user.view');
Route::post('ajaxRequest', 'User\UsuariosController@ajaxRequest')->name('ajaxRequest');

//Ruta enviar correo.
Route::post('/send', 'MailController@sendMail')->name('sendMail');

Route::put('editarPerfil/{id}', 'HomeController@update')->name('editar.perfil');

app/Http/Controllers/Admin/ActividadesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Carbon\Carbon;
use App\Event;
use Auth;
use File;
use PDF;

class ActividadesController extends Controller
{
    /**
     *  Mostrar un listado de las actividades que hay en la Base de datos que pertenezen al usuario logeado.
     *
     *  @return Devuelve la vista 'admin.actividades.index'.
     */

    public function index() {
        $eventos = Event::where([['start_date', '>', Carbon::now()]])->orderBy('start_date', 'asc')->paginate(10);

        return view('admin.actividades.index')->with('actividades',$eventos);
    }

    /**
     *  Devuelve la vista de un fomrulario para crear una actividad.
     *
     *  @return Devuelve la vista 'admin.actividades.create'
     */

    public function create() {
        return view('admin.actividades.create');
    }

    /**
     *  Crea una nueva actividad.
     *
     * @param Request $request Datos de una actividad.
     * @return Redirecciona al listado de actividades con un mensaje.
     */

    public function store(Request $request) {
        $user = Auth::user();

        $request->validate([
            'title' => 'required|string' ,
            'descripcion' => 'required|string' ,
            'inicio' => 'required',
            'fin' => 'required|after_or_equal:inicio',
        ]);

        $imageName = time().'.'.request()->imagen->getClientOriginalExtension();
        request()->imagen->move(public_path('img/actividades'), $imageName);


        $event = new Event([
            'title' => $request->input('title'),
            'descripcion' => $request->input('descripcion'),
            'start_date' => $request->input('inicio'),
            'end_date' => $request->input('fin'),
            'imagen' => $imageName,
            'user_id' => $user->id
        ]);

        $event->save();

        return redirect()->route('admin.actividades.index')->with('success','Se ha CREADO correctamente.');
    }

    /**
     *  Muestra en un formulario una actividad en concreto.
     *
     *  @param  $id Identificador de la actividad.
     *  @return Devuelve la vista 'admin.actividades.show', con el evento en concreto.
     */

    public function show($id) {
        $eventos = Event::find($id);

        return view('admin.actividades.show')->with('actividad', $eventos);
    }

    /**
     *  Devuelve un formulario para editar una actividad.
     *
     * @param  int  $id Identificador de la actividad.
     * @return Devuelve la vista 'admin.actividades.edit'.
     */

    public function edit($id) {
        return view('admin.actividades.edit')->with(['actividad' => Event::find($id)]);
    }

    /**
     *  Actualiza una actividad.
     *
     * @param  $request Datos de la actividad actualizados.
     * @param  int  $id Identificador de la actividad.
     * @return Redirecciona a la vista de 'admin.actividades.index' con un mensaje.
     */

    public function update(Request $request, $id) {
        $event = Event::find($id);

        if(request()->imagen){
            File::delete('img/actividades/'.$event->imagen);

            $imagenNueva = time().'.'.request()->imagen->getClientOriginalExtension();
            request()->imagen->move(public_path('img/actividades'), $imagenNueva);

        }else{
            $imagenNueva = $event->imagen;
        }

        $event->title = $request->input('title');
        $event->descripcion = $request->input('descripcion');
        $event->start_date = $request->input('inicio');
        $event->end_date = $request->input('fin');
        $event->imagen = $imagenNueva;

        $event->save();

        return redirect()->route('admin.actividades.index')->with('success','Se ha guardado correctamente.');
    }

    /**
     *  Elimina una actividad.
     *
     *  @param  int  $id Identificador de la actividad.
     *  @return Redirecciona a la vista de 'admin.actividades.index' con un mensaje.
     */

    public function destroy($id) {
        $evento = Event::find($id);

        if($evento){
            $evento->delete();
            File::delete('img/actividades/'.$evento->imagen);
        }

        return redirect()->route('admin.actividades.index')->with('success','Se ha eliminado correctamente.');
    }

    public function generatePDF($id) {

        $evento = Event::find($id);

        $titulo = $evento->title;

        $data = ['evento' => $evento];
        $pdf = PDF::loadView('partials/pdfView', $data);

        return $pdf->download($titulo.'.pdf');

    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\Auth;
use App\User;
use App\Role;

class UserController extends Controller {
    /**
     *  Muestra un listado de usuarios.
     *
     * @return Devuelve la vista 'admin.users.index' con los usuarios (users)
     */
    public function index() {
        return view('admin.users.index')->with('users', User::paginate(10));
    }

    /**
     *  Devuelve el formulario para editar los roles de un usuario.
     *
     *  @param  int  $id Identificador del usuario.
     *  @return Devuelve la vista 'admin.users.index' con un mensaje.
     */
    public function edit($id) {
        if(Auth::user()->id == $id){
            return redirect()->route('admin.users.index')->with('warning','No puedes editar tu propio usuario.');
        }

        return view('admin.users.edit')->with(['user' => User::find($id), 'roles' => Role::all()]);
    }

    /**
     *  Actualiza los roles de un usaurio.
     *
     * @param   $request Contenido actualizado de un usaurio.
     * @param  int  $id Identificador del usuario.
     * @return Devuelve la vista 'admin.users.index' con un mensaje.
     */
    public function update(Request $request, $id) {
        if(Auth::user()->id == $id){
            return redirect()->route('admin.users.index')->with('warning','No puedes editar tu propio usuario.');
        }

        $user = User::find($id);
        $user->roles()->sync($request->roles);

        return redirect()->route('admin.users.index')->with('success','Se ha editado correctamente.');
    }

    /**
     *  Elimina un usuario.
     *
     *  @param  int  $id Identificador de un usuario
     *  @return Devuelve la vista 'admin.users.index' con un mensaje.
     */
    public function destroy($id) {
        if(Auth::user()->id == $id){
            return redirect()->route('admin.users.index')->with('warning','No puedes eliminar tu propio usuario.');
        }

        $user = User::find($id);

        if($user){
            $user->roles()->detach();
            $user->delete();
            return redirect()->route('admin.users.index')->with('success','Se ha eliminado correctamente.');
        }

        return redirect()->route('admin.users.index')->with('warning','Este usuario no puede ser eliminado.');
    }
}

app/Http/Controllers/Mod/ActividadesController.php
<?php

namespace App\Http\Controllers\Mod;

use App\Event;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use File;
use PDF;


class ActividadesController extends Controller
{
    /**
     *  Mostrar un listado de las actividades que hay en la Base de datos que pertenezen al usuario logeado.
     *
     *  @return Devuelve la vista 'admin.actividades.index'.
     */

    public function index() {
        $user = Auth::user();
        $idUsuario = $user->id;

        $eventos = Event::where([['user_id', $idUsuario], ['start_date', '>', Carbon::now()]])->orderBy('start_date', 'asc')->paginate(10);

        return view('mod.actividades.index')->with('actividades',$eventos);
    }

    /**
     *  Devuelve la vista de un fomrulario para crear una actividad.
     *
     *  @return Devuelve la vista 'admin.actividades.create'
     */

    public function create() {
        return view('mod.actividades.create');
    }

    /**
     *  Crea una nueva actividad.
     *
     * @param Request $request Datos de una actividad.
     * @return Redirecciona al listado de actividades con un mensaje.
     */

    public function store(Request $request) {
        $user = Auth::user();

        $request->validate([
            'title' => 'required|string' ,
            'descripcion' => 'required|string' ,
            'inicio' => 'required|min:5|max:254',
            'fin' => 'required',
        ]);

        $imageName = time().'.'.request()->imagen->getClientOriginalExtension();
        request()->imagen->move(public_path('img/actividades'), $imageName);

        $event = new Event([
            'title' => $request->input('title'),
            'descripcion' => $request->input('descripcion'),
            'start_date' => $request->input('inicio'),
            'end_date' => $request->input('fin'),
            'imagen' => $imageName,
            'user_id' => $user->id
        ]);

        $event->save();

        return redirect()->route('mod.actividades.index')->with('success','Se ha CREADO correctamente.');
    }

    /**
     *  Muestra en un formulario una actividad en concreto.
     *
     *  @param  $id Identificador de la actividad.
     *  @return Devuelve la vista 'admin.actividades.show', con el evento en concreto.
     */

    public function show($id) {
        return view('mod.actividades.show')->with(['actividad' => Event::find($id)]);
    }

    /**
     *  Devuelve un formulario para editar una actividad.
     *
     * @param  int  $id Identificador de la actividad.
     * @return Devuelve la vista 'admin.actividades.edit'.
     */

    public function edit($id) {
        return view('mod.actividades.edit')->with(['actividad' => Event::find($id)]);
    }

    /**
     *  Actualiza una actividad.
     *
     * @param  $request Datos de la actividad actualizados.
     * @param  int  $id Identificador de la actividad.
     * @return Redirecciona a la vista de 'admin.actividades.index' con un mensaje.
     */

    public function update(Request $request, $id) {
        $event = Event::find($id);

        if(request()->imagen){
            File::delete('img/actividades/'.$event->imagen);

            $imagenNueva = time().'.'.request()->imagen->getClientOriginalExtension();
            request()->imagen->move(public_path('img/actividades'), $imagenNueva);

        }else{
            $imagenNueva = $event->imagen;
        }

        $event->title = $request->input('title');
        $event->descripcion = $request->input('descripcion');
        $event->start_date = $request->input('inicio');
        $event->end_date = $request->input('fin');
        $event->imagen = $imagenNueva;

        $event->save();

        return redirect()->route('mod.actividades.index')->with('success','Se ha guardado correctamente.');
    }

    /**
     *  Elimina una actividad.
     *
     *  @param  int  $id Identificador de la actividad.
     *  @return Redirecciona a la vista de 'admin.actividades.index' con un mensaje.
     */

    public function destroy($id) {
        $evento = Event::find($id);

        if($evento){
            $evento->delete();
            File::delete('img/actividades/'.$evento->imagen);
        }

        return redirect()->route('admin.actividades.index')->with('success','Se ha eliminado correctamente.');
    }

    /**
     *  Si el creador de la actividad es el usuario logeado le permitira edtiar la actividad, si no solo podra verla.
     *
     *  @param  int  $id Identificador de la actividad.
     *  @return Redirecciona a la vista de 'mod.actividades.edit' o 'mod.actividades.show'.
     */

    public function ver($id){
        $evento = Event::find($id);
        $idUsuario = Auth::user()->id;

        if($evento->user_id == $idUsuario) {
            return view('mod.actividades.edit')->with(['actividad' => Event::find($id)]);
        }else{
            return view('mod.actividades.show')->with(['actividad' => Event::find($id)]);
        }
    }

    public function generatePDF($id) {

        $evento = Event::find($id);

        $titulo = $evento->title;
        $reservas = $evento->users;

        $data = ['evento' => $evento];
        $pdf = PDF::loadView('partials/pdfView', $data);

        return $pdf->download($titulo.'.pdf');

    }

}

app/Http/Controllers/User/ActividadesController.php
<?php

namespace App\Http\Controllers\User;

use App\Event;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ActividadesController extends Controller {

    /**
     *  Muestra un listado de todas las actividiades que hay en la Base de Datos.
     *
     *  @return Redirecciona a la tabla de reservas del usuario logeado, con un mensaje.
     */

    public function index() {
        $eventos = Event::where([['start_date', '>', Carbon::now()]])->orderBy('start_date', 'asc')->paginate(4);

        return view('user.actividades.index')->with('actividades', $eventos);
    }

    /**
     *  Muestra una actividad en concreto.
     *
     *  @param  $id Identidicador de la actividad.
     *  @return Redirecciona al formulario donde muestra una actividad en concreto.
     */

    public function show($id) {
        $eventos = Event::find($id);

        return view('user.actividades.show')->with('actividad', $eventos);
    }
}

app/Http/Controllers/User/UsuariosController.php
<?php

namespace App\Http\Controllers\User;

use App\Event;
use App\User;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use function foo\func;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UsuariosController extends Controller {

    public function users() {
        $users = User::whereHas('roles', function($q) { $q->whereIn('name', ['admin', 'mod']); })->paginate(10);

        $id =Auth::user()->id;
        $user = User::find($id);

        return view('user.follow.users', compact('users','user'));
    }

    public function user($id) {
        $user = User::find($id);
        $actividades = Event::where([['user_id', $user->id], ['start_date', '>', Carbon::now()]])->orderBy('start_date', 'asc')->paginate(10);

        return view('user.follow.actividadesList')->with('user', $user)->with('actividades', $actividades);
    }

    public function ajaxRequest(Request $request) {
        $user = User::find($request->user_id);

        $response = auth()->user()->toggleFollow($user);

        return response()->json(['success'=>$response]);
    }
}

resources/views/user/actividades/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row-fluid ">
            <div class="card-group mt-2">
                <div class="card-deck">
                    @foreach($actividades as $actividad)
                        <div class="card" style="width: 18rem;">
                            <img src="{{asset('img/actividades/'.$actividad->imagen)}}" class="figure-img img-fluid rounded" style=" width:100%; height: 250px;">

                            <div class="card-body" style="text-align: center">
                                <h5 class="card-title">{{$actividad->title}}</h5>
                                <h6><b>Fecha inicio:</b>
                                    <br>
                                        {{date('d-m-Y', strtotime($actividad->start_date))}}
                                            <br>
                                        {{date('H:i', strtotime($actividad->start_date))}}
                                </h6>
                                <h6><b>Fecha fin:</b>
                                    <br>
                                        {{date('d-m-Y', strtotime($actividad->end_date))}}
                                            <br>
                                        {{date('H:i', strtotime($actividad->end_date))}}
                                </h6>

                            </div>

                            <div class="card-footer text-muted">
                                <a href="{{route('user.actividades.show', $actividad->id)}}" class="float-left">
                                    <button type="submit" class="btn-success btn-sm"><i class="far fa-eye"></i></button>
                                </a>

                                @if (auth()->user()->events->contains($actividad))
                                    <form action="{{route('user.reservas.destroy', $actividad->id)}}"  method="POST" class="float-left ml-2">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn-danger btn-sm" onclick="return confirm('Estas seguro que quieres cancelar tu reserva?')"><i class="far fa-times-circle"></i></button>
                                    </form>
                                @else
                                    <a href="actividades/reservar/{{$actividad->id}}" class="float-left">
                                        <button type="button" class="btn-primary btn-sm"><i class="fas fa-user-plus"></i></button>
                                    </a>
                                @endif
                            </div>

                        </div>
                    @endforeach
                </div>
            </div>
        </div><br>
        {{$actividades->links()}}
    </div>
@endsection

resources/views/user/actividades/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <h1>{{ $actividad->title }}</h1>

        <div class="row justify-content-center">
            <div class="col">
                <div class="form-group">
                    <h5 class="mt-2">
                        <strong>Titulo: </strong>
                        {{$actividad->title}} <br>
                    </h5>

                    <h5 class="mt-2">
                        <strong>Descripcion: </strong> <br>
                        {{$actividad->descripcion}} <br>
                    </h5>

                    <h5 class="mt-2">
                        <strong>Fecha Inicio: </strong>
                        <br>
                        {{date('d-m-Y H:i', strtotime($actividad->start_date))}}

                    </h5>

                    <h5 class="mt-2">
                        <strong>Fecha Fin: </strong>
                        <br>
                        {{date('d-m-Y H:i', strtotime($actividad->end_date))}} <br>
                    </h5>


                <figure class="figure">
                    <img src="{{asset('img/actividades/'.$actividad->imagen)}}" class="figure-img img-fluid rounded" style=" width:100%; height: 250px;">
                </figure>
                </div>

                @if (auth()->user()->events->contains($actividad))
                    <form action="{{route('user.reservas.destroy', $actividad->id)}}"  method="POST" class="float-left">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn-danger btn-sm" onclick="return confirm('Estas seguro que quieres cancelar tu reserva?')">Cancelar Reserva</button>
                    </form>
                @else
                    <a href="reservar/{{$actividad->id}}" class="float-left">
                        <button type="button" class="btn-primary btn-sm">Inscribirme</button>
                    </a>
                @endif

                <a href="{{ URL::previous() }}"><button type="submit" class="btn-primary btn-sm">Volver</button></a>

            </div>
        </div>
    </div>














@endsection