routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () { return view('welcome'); })->name('welcome');

//Ruta para usuarios y administroador para EventController@index (Calendario)
Route::get('/home', 'EventController@index')->name('home');

//Rutas Administrador
Route::namespace('Admin')->prefix('admin')->middleware(['auth', 'auth.admin'])->name('admin.')->group(function(){
    //Ruta para el Admin\ActividadesController
    Route::resource('/actividades', 'ActividadesController');

    //Ruta para el Admin\UserController
    Route::resource('/users', 'UserController');

    //Ruta para el Admin\ReservasController
    Route::resource('/reservas', 'ReservasController');

    //Ruta para crear el PDF como Administrador
    Route::get('generate-pdf/{id}','ActividadesController@generatePDF')->name('generarPDF');
});

//Rutas Usuarios
Route::namespace('User')->prefix('user')->middleware(['auth', 'auth.user'])->name('user.')->group(function(){
    //Ruta para crear una reserva.
    Route::get('/actividades/reservar/{id}', 'ReservasController@crear');

    //Ruta para el User\ActividadesController
    Route::resource('/actividades', 'ActividadesController');
    //Ruta para el User\ReservasController
    Route::resource('/reservas', 'ReservasController');

});

//Rutas Moderador
Route::namespace('Mod')->prefix('mod')->middleware(['auth', 'auth.mod'])->name('mod.')->group(function(){
    //Ruta para crear una reserva.
    Route::get('/actividades/ver/{id}', 'ActividadesController@ver');

    //Ruta para el Admin\ActividadesController
    Route::resource('/actividades', 'ActividadesController');

    //Ruta para el Admin\ReservasController
    Route::resource('/reservas', 'ReservasController');

    //Ruta para crer el PDF como Moderador
    Route::get('generate-pdf/{id}','ActividadesController@generatePDF')->name('generarPDF');
});

//Rutas para el follow de los usuarios
Route::get('users', 'User\UsuariosController@users')->name('users');
Route::get('user/{id}', 'User\UsuariosController@user')->name('user.view');
Route::post('ajaxRequest', 'User\UsuariosController@ajaxRequest')->name('ajaxRequest');

//Ruta enviar correo.
Route::post('/send', 'MailController@sendMail')->name('sendMail');

Route::put('editarPerfil/{id}', 'HomeController@update')->name('editar.perfil');

app/Http/Controllers/Admin/ActividadesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Carbon\Carbon;
use App\Event;
use Auth;
use File;
use PDF;

class ActividadesController extends Controller
{
    /**
     *  Mostrar un listado de las actividades que hay en la Base de datos que pertenezen al usuario logeado.
     *
     *  @return Devuelve la vista 'admin.actividades.index'.
     */

    public function index() {
        $eventos = Event::where([['start_date', '>', Carbon::now()]])->orderBy('start_date', 'asc')->paginate(10);

        return view('admin.actividades.index')->with('actividades',$eventos);
    }

    /**
     *  Devuelve la vista de un fomrulario para crear una actividad.
     *
     *  @return Devuelve la vista 'admin.actividades.create'
     */

    public function create() {
        return view('admin.actividades.create');
    }

    /**
     *  Crea una nueva actividad.
     *
     * @param Request $request Datos de una actividad.
     * @return Redirecciona al listado de actividades con un mensaje.
     */

    public function store(Request $request) {
        $user = Auth::user();

        $request->validate([
            'title' => 'required|string' ,
            'descripcion' => 'required|string' ,
            'inicio' => 'required',
            'fin' => 'required|after_or_equal:inicio',
        ]);

        $imageName = time().'.'.request()->imagen->getClientOriginalExtension();
        request()->imagen->move(public_path('img/actividades'), $imageName);


        $event = new Event([
            'title' => $request->input('title'),
            'descripcion' => $request->input('descripcion'),
            'start_date' => $request->input('inicio'),
            'end_date' => $request->input('fin'),
            'imagen' => $imageName,
            'user_id' => $user->id
        ]);

        $event->save();

        return redirect()->route('admin.actividades.index')->with('success','Se ha CREADO correctamente.');
    }

    /**
     *  Muestra en un formulario una actividad en concreto.
     *
     *  @param  $id Identificador de la actividad.
     *  @return Devuelve la vista 'admin.actividades.show', con el evento en concreto.
     */

    public function show($id) {
        $eventos = Event::find($id);

        return view('admin.actividades.show')->with('actividad', $eventos);
    }

    /**
     *  Devuelve un formulario para editar una actividad.
     *
     * @param  int  $id Identificador de la actividad.
     * @return Devuelve la vista 'admin.actividades.edit'.
     */

    public function edit($id) {
        return view('admin.actividades.edit')->with(['actividad' => Event::find($id)]);
    }

    /**
     *  Actualiza una actividad.
     *
     * @param  $request Datos de la actividad actualizados.
     * @param  int  $id Identificador de la actividad.
     * @return Redirecciona a la vista de 'admin.actividades.index' con un mensaje.
     */

    public function update(Request $request, $id) {
        $event = Event::find($id);

        if(request()->imagen){
            File::delete('img/actividades/'.$event->imagen);

            $imagenNueva = time().'.'.request()->imagen->getClientOriginalExtension();
            request()->imagen->move(public_path('img/actividades'), $imagenNueva);

        }else{
            $imagenNueva = $event->imagen;
        }

        $event->title = $request->input('title');
        $event->descripcion = $request->input('descripcion');
        $event->start_date = $request->input('inicio');
        $event->end_date = $request->input('fin');
        $event->imagen = $imagenNueva;

        $event->save();

        return redirect()->route('admin.actividades.index')->with('success','Se ha guardado correctamente.');
    }

    /**
     *  Elimina una actividad.
     *
     *  @param  int  $id Identificador de la actividad.
     *  @return Redirecciona a la vista de 'admin.actividades.index' con un mensaje.
     */

    public function destroy($id) {
        $evento = Event::find($id);

        if($evento){
            $evento->delete();
            File::delete('img/actividades/'.$evento->imagen);
        }

        return redirect()->route('admin.actividades.index')->with('success','Se ha eliminado correctamente.');
    }

    public function generatePDF($id) {

        $evento = Event::find($id);

        $titulo = $evento->title;

        $data = ['evento' => $evento];
        $pdf = PDF::loadView('partials/pdfView', $data);

        return $pdf->download($titulo.'.pdf');

    }
}

app/Http/Controllers/Mod/ActividadesController.php
<?php

namespace App\Http\Controllers\Mod;

use App\Event;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use File;
use PDF;


class ActividadesController extends Controller
{
    /**
     *  Mostrar un listado de las actividades que hay en la Base de datos que pertenezen al usuario logeado.
     *
     *  @return Devuelve la vista 'admin.actividades.index'.
     */

    public function index() {
        $user = Auth::user();
        $idUsuario = $user->id;

        $eventos = Event::where([['user_id', $idUsuario], ['start_date', '>', Carbon::now()]])->orderBy('start_date', 'asc')->paginate(10);

        return view('mod.actividades.index')->with('actividades',$eventos);
    }

    /**
     *  Devuelve la vista de un fomrulario para crear una actividad.
     *
     *  @return Devuelve la vista 'admin.actividades.create'
     */

    public function create() {
        return view('mod.actividades.create');
    }

    /**
     *  Crea una nueva actividad.
     *
     * @param Request $request Datos de una actividad.
     * @return Redirecciona al listado de actividades con un mensaje.
     */

    public function store(Request $request) {
        $user = Auth::user();

        $request->validate([
            'title' => 'required|string' ,
            'descripcion' => 'required|string' ,
            'inicio' => 'required|min:5|max:254',
            'fin' => 'required',
        ]);

        $imageName = time().'.'.request()->imagen->getClientOriginalExtension();
        request()->imagen->move(public_path('img/actividades'), $imageName);

        $event = new Event([
            'title' => $request->input('title'),
            'descripcion' => $request->input('descripcion'),
            'start_date' => $request->input('inicio'),
            'end_date' => $request->input('fin'),
            'imagen' => $imageName,
            'user_id' => $user->id
        ]);

        $event->save();

        return redirect()->route('mod.actividades.index')->with('success','Se ha CREADO correctamente.');
    }

    /**
     *  Muestra en un formulario una actividad en concreto.
     *
     *  @param  $id Identificador de la actividad.
     *  @return Devuelve la vista 'admin.actividades.show', con el evento en concreto.
     */

    public function show($id) {
        return view('mod.actividades.show')->with(['actividad' => Event::find($id)]);
    }

    /**
     *  Devuelve un formulario para editar una actividad.
     *
     * @param  int  $id Identificador de la actividad.
     * @return Devuelve la vista 'admin.actividades.edit'.
     */

    public function edit($id) {
        return view('mod.actividades.edit')->with(['actividad' => Event::find($id)]);
    }

    /**
     *  Actualiza una actividad.
     *
     * @param  $request Datos de la actividad actualizados.
     * @param  int  $id Identificador de la actividad.
     * @return Redirecciona a la vista de 'admin.actividades.index' con un mensaje.
     */

    public function update(Request $request, $id) {
        $event = Event::find($id);

        if(request()->imagen){
            File::delete('img/actividades/'.$event->imagen);

            $imagenNueva = time().'.'.request()->imagen->getClientOriginalExtension();
            request()->imagen->move(public_path('img/actividades'), $imagenNueva);

        }else{
            $imagenNueva = $event->imagen;
        }

        $event->title = $request->input('title');
        $event->descripcion = $request->input('descripcion');
        $event->start_date = $request->input('inicio');
        $event->end_date = $request->input('fin');
        $event->imagen = $imagenNueva;

        $event->save();

        return redirect()->route('mod.actividades.index')->with('success','Se ha guardado correctamente.');
    }

    /**
     *  Elimina una actividad.
     *
     *  @param  int  $id Identificador de la actividad.
     *  @return Redirecciona a la vista de 'admin.actividades.index' con un mensaje.
     */

    public function destroy($id) {
        $evento = Event::find($id);

        if($evento){
            $evento->delete();
            File::delete('img/actividades/'.$evento->imagen);
        }

        return redirect()->route('admin.actividades.index')->with('success','Se ha eliminado correctamente.');
    }

    /**
     *  Si el creador de la actividad es el usuario logeado le permitira edtiar la actividad, si no solo podra verla.
     *
     *  @param  int  $id Identificador de la actividad.
     *  @return Redirecciona a la vista de 'mod.actividades.edit' o 'mod.actividades.show'.
     */

    public function ver($id){
        $evento = Event::find($id);
        $idUsuario = Auth::user()->id;

        if($evento->user_id == $idUsuario) {
            return view('mod.actividades.edit')->with(['actividad' => Event::find($id)]);
        }else{
            return view('mod.actividades.show')->with(['actividad' => Event::find($id)]);
        }
    }

    public function generatePDF($id) {

        $evento = Event::find($id);

        $titulo = $evento->title;
        $reservas = $evento->users;

        $data = ['evento' => $evento];
        $pdf = PDF::loadView('partials/pdfView', $data);

        return $pdf->download($titulo.'.pdf');

    }

}

app/Http/Controllers/Mod/ReservasController.php
<?php

namespace App\Http\Controllers\Mod;

use App\Event;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;

class ReservasController extends Controller
{
    /**
     *  Devuelve una lista de las actividades.
     *
     * @return Devuelve la vista 'admin.reservas.index'
     */

    public function index() {
        $user = Auth::user();
        $idUsuario = $user->id;

        $eventos = Event::where([['user_id', $idUsuario], ['start_date', '>', Carbon::now()]])->orderBy('start_date', 'asc')->paginate(10);

        return view('mod.reservas.index')->with('reservas',$eventos);
    }

    /**
     *  Muestra un listado de las reservas de una actividad en concreto.
     *
     * @param  int  $id Identificador de el evento seleccionado.
     * @return Devuelve la vista 'admin.reservas.show'
     */

    public function show($id) {
        $evento = Event::find($id);

        return view('mod.reservas.show')->with('evento', $evento);
    }

}

app/Http/Controllers/User/ActividadesController.php
<?php

namespace App\Http\Controllers\User;

use App\Event;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ActividadesController extends Controller {

    /**
     *  Muestra un listado de todas las actividiades que hay en la Base de Datos.
     *
     *  @return Redirecciona a la tabla de reservas del usuario logeado, con un mensaje.
     */

    public function index() {
        $eventos = Event::where([['start_date', '>', Carbon::now()]])->orderBy('start_date', 'asc')->paginate(4);

        return view('user.actividades.index')->with('actividades', $eventos);
    }

    /**
     *  Muestra una actividad en concreto.
     *
     *  @param  $id Identidicador de la actividad.
     *  @return Redirecciona al formulario donde muestra una actividad en concreto.
     */

    public function show($id) {
        $eventos = Event::find($id);

        return view('user.actividades.show')->with('actividad', $eventos);
    }
}

resources/views/mod/actividades/create.blade.php
@extends('layouts.app')

@section('styles')
    <link href="{{asset('css/datechooser/bootstrap-datetimepicker.min.css')}}" rel="stylesheet">
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col">
                <form method="post" action="{{route('mod.actividades.store')}}" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="title">Titulo:</label>
                        <input type="text" class="form-control" name="title" required
                               />

                        <label for="title">Descripcion</label>
                        <textarea class="form-control rounded-0" rows="3" name="descripcion" required ></textarea>

                        <label for="title">Fecha Inicio:</label>
                        <input size="16" type="text" class="form-control" style="width: 200px; margin-bottom: 10px;background-color: white" id="datetime2" name="inicio" required readonly>

                        <label for="title">Fecha Fin:</label>
                        <input size="16" type="text" class="form-control" style="width: 200px; margin-bottom: 10px;background-color: white" id="datetime3" name="fin" required readonly>

                        <label for="exampleFormControlFile1">Imagen: </label>
                        <input type="file" class="form-control-file" name="imagen"><br>

                        <button type="submit" class="btn btn-primary">Añadir</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/locale/es.js"></script>
    <script src="{{asset('js/datechooser/bootstrap-datetimepicker.min.js')}}"></script>

    <script type="text/javascript">

        $("#datetime2").datetimepicker({
            dateFormat: 'dd/mm/yy',
            autoclose: true,
            startDate: new Date()
        });

        $("#datetime3").datetimepicker({
            dateFormat: 'dd/mm/yy',
            autoclose: true,
            startDate: $("#datetime2").datetimepicker("getDate")
        });

    </script>
@endsection

resources/views/mod/actividades/edit.blade.php
@extends('layouts.app')

@section('styles')
    <link href="{{asset('css/datechooser/bootstrap-datetimepicker.min.css')}}" rel="stylesheet">
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col">
                <form action="{{route('mod.actividades.update', ['event' => $actividad->id])}}" method="POST" enctype="multipart/form-data">
                    @csrf {{method_field('PUT')}}
                    <div class="form-group">
                        <label for="title">Titulo:</label>
                        <input type="text" class="form-control" name="title" value="{{$actividad->title}}">

                        <label for="title">Descripcion:</label>
                        <textarea class="form-control rounded-0" rows="3" name="descripcion">{{$actividad->descripcion}}</textarea>

                        <label for="title">Fecha Inicio:</label>
                        <input size="16" type="text" class="form-control" style="width: 200px; margin-bottom: 10px;background-color: white" id="datetime2" name="inicio" value="{{$actividad->start_date}}" readonly>

                        <label for="title">Fecha Fin:</label>
                        <input size="16" type="text" class="form-control" style="width: 200px; margin-bottom: 10px;background-color: white" id="datetime3" name="fin" value="{{$actividad->end_date}}" readonly>

                        <label for="exampleFormControlFile1">Imagen: </label><br>

                        <figure class="figure">
                            <img src="{{asset('img/actividades/'.$actividad->imagen)}}" class="figure-img img-fluid rounded" style=" width:100%; height: 250px;">
                        </figure>

                        <input type="file" class="form-control-file" name="imagen"><br>

                    </div>
                    <button type="submit" class="btn-primary">Actualizar</button>
                </form>
            </div>

        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/locale/es.js"></script>
    <script src="{{asset('js/datechooser/bootstrap-datetimepicker.min.js')}}"></script>

    <script type="text/javascript">

        $("#datetime2").datetimepicker({
            dateFormat: 'dd/mm/yy',
            autoclose: true,
            startDate: new Date()
        });

        $("#datetime3").datetimepicker({
            dateFormat: 'dd/mm/yy',
            autoclose: true,
            startDate: $("#datetime2").datetimepicker("getDate")
        });

    </script>
@endsection

resources/views/mod/actividades/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div>
            <h1> Actividades

                <a href="{{route('mod.actividades.create')}}" class="float-right">
                    <button type="button" class="btn btn-primary">Añadir Actividad</button>
                </a>
            </h1>
        </div>

        <div class="row justify-content-center">
            <div class="col">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col" >Img</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Fecha Inicio</th>
                        <th scope="col">Fecha Fin</th>
                        <th scope="col">Accion</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($actividades as $actividad)
                        <tr>
                            <th><img src="{{asset('img/actividades/'.$actividad->imagen)}}" class="figure-img img-fluid rounded" style="width: 200px; height: 100px;"></th>
                            <th>{{$actividad->title}}</th>
                            <th>{{date('d-m-Y', strtotime($actividad->start_date))}}
                                <br>
                            {{date('H:i', strtotime($actividad->start_date))}}
                            <th>{{date('d-m-Y', strtotime($actividad->end_date))}}
                                <br>
                                {{date('H:i', strtotime($actividad->end_date))}}</th>
                            <th>
                                <a href="{{route('mod.actividades.edit', $actividad->id)}}" class="float-left">
                                    <button type="button" class="btn-primary btn-sm"><i class="far fa-edit"></i></button>
                                </a>

                                <a href="{{route('mod.actividades.show', $actividad->id)}}" class="float-left mr-2">
                                    <button type="submit" class="btn-success btn-sm"><i class="far fa-eye"></i></button>
                                </a>

                                <form action="{{route('mod.actividades.destroy', $actividad->id)}}"  method="POST" class="float-left">
                                    @csrf @method('DELETE')
                                    <button type="submit" class="btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
                                </form>
                            </th>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        {{$actividades->links()}}
    </div>
@endsection

resources/views/mod/actividades/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <h1>{{ $actividad->title }}</h1>

        <div class="row justify-content-center">
            <div class="col">
                <div class="form-group">
                    <h5 class="mt-2">
                        <strong>Titulo: </strong>
                        {{$actividad->title}} <br>
                    </h5>

                    <h5 class="mt-2">
                        <strong>Descripcion: </strong> <br>
                        {{$actividad->descripcion}} <br>
                    </h5>

                    <h5 class="mt-2">
                        <strong>Fecha Inicio: </strong>
                        <br>
                        {{date('d-m-Y H:i', strtotime($actividad->start_date))}}

                    </h5>

                    <h5 class="mt-2">
                        <strong>Fecha Fin: </strong>
                        <br>
                        {{date('d-m-Y H:i', strtotime($actividad->end_date))}} <br>
                    </h5>

                    <figure class="figure">
                        <img src="{{asset('img/actividades/'.$actividad->imagen)}}" class="figure-img img-fluid rounded" style=" width:100%; height: 250px;">
                    </figure>
                </div>

                <a href="{{ URL::previous() }}"><button type="submit" class="btn-primary btn-sm">Volver</button></a>

            </div>
        </div>
    </div>
@endsection