routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () { return view('welcome'); })->name('welcome');

//Ruta para usuarios y administroador para EventController@index (Calendario)
Route::get('/home', 'EventController@index')->name('home');

//Rutas Administrador
Route::namespace('Admin')->prefix('admin')->middleware(['auth', 'auth.admin'])->name('admin.')->group(function(){
    //Ruta para el Admin\ActividadesController
    Route::resource('/actividades', 'ActividadesController');

    //Ruta para el Admin\UserController
    Route::resource('/users', 'UserController');

    //Ruta para el Admin\ReservasController
    Route::resource('/reservas', 'ReservasController');

    //Ruta para crear el PDF como Administrador
    Route::get('generate-pdf/{id}','ActividadesController@generatePDF')->name('generarPDF');
});

//Rutas Usuarios
Route::namespace('User')->prefix('user')->middleware(['auth', 'auth.user'])->name('user.')->group(function(){
    //Ruta para crear una reserva.
    Route::get('/actividades/reservar/{id}', 'ReservasController@crear');

    //Ruta para el User\ActividadesController
    Route::resource('/actividades', 'ActividadesController');
    //Ruta para el User\ReservasController
    Route::resource('/reservas', 'ReservasController');

});

//Rutas Moderador
Route::namespace('Mod')->prefix('mod')->middleware(['auth', 'auth.mod'])->name('mod.')->group(function(){
    //Ruta para crear una reserva.
    Route::get('/actividades/ver/{id}', 'ActividadesController@ver');

    //Ruta para el Admin\ActividadesController
    Route::resource('/actividades', 'ActividadesController');

    //Ruta para el Admin\ReservasController
    Route::resource('/reservas', 'ReservasController');

    //Ruta para crer el PDF como Moderador
    Route::get('generate-pdf/{id}','ActividadesController@generatePDF')->name('generarPDF');
});

//Rutas para el follow de los usuarios
Route::get('users', 'User\UsuariosController@users')->name('users');
Route::get('user/{id}', 'User\UsuariosController@user')->name('user.view');
Route::post('ajaxRequest', 'User\UsuariosController@ajaxRequest')->name('ajaxRequest');

//Ruta enviar correo.
Route::post('/send', 'MailController@sendMail')->name('sendMail');

Route::put('editarPerfil/{id}', 'HomeController@update')->name('editar.perfil');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

use Overtrue\LaravelFollow\Traits\CanFollow;
use Overtrue\LaravelFollow\Traits\CanBeFollowed;

class User extends Authenticatable
{
    use Notifiable, CanFollow, CanBeFollowed;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $fillable = [
        'name', 'email', 'password',
    ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */

    protected $hidden = [
        'password', 'remember_token',
    ];

    //Reservas
    public function events(){
        return $this->belongsToMany(Event::class);
    }

    //Actividades
    public function event(){
        return $this->hasMany('App\Event');
    }

    public function roles(){
        return $this->belongsToMany('App\Role');
    }

    public function hasAnyRoles($roles){
        return null !== $this->roles()->whereIn('name', $roles)->first();
    }

    public function hasAnyRole($role){
        return null !== $this->roles()->where('name', $role)->first();
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\Auth;
use App\User;
use App\Role;

class UserController extends Controller {
    /**
     *  Muestra un listado de usuarios.
     *
     * @return Devuelve la vista 'admin.users.index' con los usuarios (users)
     */
    public function index() {
        return view('admin.users.index')->with('users', User::paginate(10));
    }

    /**
     *  Devuelve el formulario para editar los roles de un usuario.
     *
     *  @param  int  $id Identificador del usuario.
     *  @return Devuelve la vista 'admin.users.index' con un mensaje.
     */
    public function edit($id) {
        if(Auth::user()->id == $id){
            return redirect()->route('admin.users.index')->with('warning','No puedes editar tu propio usuario.');
        }

        return view('admin.users.edit')->with(['user' => User::find($id), 'roles' => Role::all()]);
    }

    /**
     *  Actualiza los roles de un usaurio.
     *
     * @param   $request Contenido actualizado de un usaurio.
     * @param  int  $id Identificador del usuario.
     * @return Devuelve la vista 'admin.users.index' con un mensaje.
     */
    public function update(Request $request, $id) {
        if(Auth::user()->id == $id){
            return redirect()->route('admin.users.index')->with('warning','No puedes editar tu propio usuario.');
        }

        $user = User::find($id);
        $user->roles()->sync($request->roles);

        return redirect()->route('admin.users.index')->with('success','Se ha editado correctamente.');
    }

    /**
     *  Elimina un usuario.
     *
     *  @param  int  $id Identificador de un usuario
     *  @return Devuelve la vista 'admin.users.index' con un mensaje.
     */
    public function destroy($id) {
        if(Auth::user()->id == $id){
            return redirect()->route('admin.users.index')->with('warning','No puedes eliminar tu propio usuario.');
        }

        $user = User::find($id);

        if($user){
            $user->roles()->detach();
            $user->delete();
            return redirect()->route('admin.users.index')->with('success','Se ha eliminado correctamente.');
        }

        return redirect()->route('admin.users.index')->with('warning','Este usuario no puede ser eliminado.');
    }
}

app/Http/Controllers/User/ActividadesController.php
<?php

namespace App\Http\Controllers\User;

use App\Event;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ActividadesController extends Controller {

    /**
     *  Muestra un listado de todas las actividiades que hay en la Base de Datos.
     *
     *  @return Redirecciona a la tabla de reservas del usuario logeado, con un mensaje.
     */

    public function index() {
        $eventos = Event::where([['start_date', '>', Carbon::now()]])->orderBy('start_date', 'asc')->paginate(4);

        return view('user.actividades.index')->with('actividades', $eventos);
    }

    /**
     *  Muestra una actividad en concreto.
     *
     *  @param  $id Identidicador de la actividad.
     *  @return Redirecciona al formulario donde muestra una actividad en concreto.
     */

    public function show($id) {
        $eventos = Event::find($id);

        return view('user.actividades.show')->with('actividad', $eventos);
    }
}

app/Http/Controllers/User/ReservasController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Event;
use App\User;
use Auth;

class ReservasController extends Controller {
    /**
     *  Muestra un listado con las reservas del usuario logeado.
     *
     *  @return Devuelve la vista de reservas.index con el usuario logeado.
     */

    public function index() {
        $id = Auth::id();
        $usuario = User::find($id);

        return view('user.reservas.index')->with('usuario', $usuario);
    }

    /**
     *  Elimina una reserva que tiene el usuario logeado.
     *
     *  @param  $id Identidicador de la actividad.
     *  @return Redirecciona a la tabla de reservas del usuario logeado, con un mensaje.
     */

    public function destroy($id) {
        $actividad = Event::find($id);
        $idUsuario = Auth::id();

        //Elimina la relacion que hay entre el usuario logeado y la actividad seleccionada.
        $actividad->users()->detach($idUsuario);



        return redirect()->route('user.reservas.index')->with('success','Se eliminado su reserva.');
    }

    /**
     *  Crea una reserva al usuario que hay logeado.
     *
     *  @param $id Identidicador de la actividad.
     *  @return Redirecciona a la tabla de reservas del usuario logeado, con un mensaje.
     */

    public function crear($id){
        $idUsuario = Auth::id();
        $user = User::find($idUsuario);

        $actividad = Event::find($id);

        if($user->events->contains($id)){
            return redirect()->route('user.actividades.index')->with('success','Ya tienes una reserva para esta actividad.');

        }else if($this->comprobar($actividad)){
            return redirect()->route('user.actividades.index')->with('success','Ya tienes una reserva para esta fecha.');

        }

        $actividad->users()->attach($idUsuario);
        return redirect()->route('user.reservas.index')->with('success','Se creado su reserva.');
    }

    /**
     *  Comprobar que no tengamos una reserva para una actividad en la misma fecha y hora que otra actividad ya reservada.
     *
     *  @param $activiadRecibida Actividad a la que queremos hacer la reserva.
     *  @return true = si tenemos una reserva para las mismas fechas.
     */

    public function comprobar($activiadRecibida){
        $idUsuario = Auth::id();
        $user = User::find($idUsuario);

        $inicioActividad = $activiadRecibida->start_date;
        $finActividad = $activiadRecibida->end_date;

        foreach($user->events as $evento){
            if($evento->start_date == $inicioActividad && $evento->end_date == $finActividad){
                return true;
            }
        }

        return false;
    }
}

app/Http/Controllers/User/UsuariosController.php
<?php

namespace App\Http\Controllers\User;

use App\Event;
use App\User;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use function foo\func;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UsuariosController extends Controller {

    public function users() {
        $users = User::whereHas('roles', function($q) { $q->whereIn('name', ['admin', 'mod']); })->paginate(10);

        $id =Auth::user()->id;
        $user = User::find($id);

        return view('user.follow.users', compact('users','user'));
    }

    public function user($id) {
        $user = User::find($id);
        $actividades = Event::where([['user_id', $user->id], ['start_date', '>', Carbon::now()]])->orderBy('start_date', 'asc')->paginate(10);

        return view('user.follow.actividadesList')->with('user', $user)->with('actividades', $actividades);
    }

    public function ajaxRequest(Request $request) {
        $user = User::find($request->user_id);

        $response = auth()->user()->toggleFollow($user);

        return response()->json(['success'=>$response]);
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"> Editar Usuario ({{$user-> name}})</div>
                    <div class="card-body">
                        <form action="{{route('admin.users.update', ['user' => $user->id])}}" method="POST">
                            @csrf
                            {{method_field('PUT')}}
                            @foreach($roles as $role)
                                <div class="form-check">
                                    <input type="checkbox" name="roles[]" value="{{$role->id}}"
                                            {{$user->hasAnyRole($role->name)?'checked':''}}>
                                    <label>{{$role->name}}</label>
                                </div>
                            @endforeach

                            <button type="submit" class="btn-primary">Actualizar</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Usuarios</h1>
        <div class="row justify-content-center">
            <div class="col">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Nombre</th>
                            <th scope="col">Correo Electronico</th>
                            <th scope="col">Rol</th>
                            <th scope="col">Accion</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $user)
                            <tr>
                                <th>{{$user->name}}</th>
                                <th>{{$user->email}}</th>
                                <th>{{implode(', ', $user->roles()->get()->pluck('name')->toArray())}}</th>
                                <th>
                                    <a href="{{route('admin.users.edit', $user->id)}}" class="float-left">
                                        <button type="button" class="btn-primary btn-sm"><i class="far fa-edit"></i>
                                        </button>
                                    </a>

                                    <form action="{{route('admin.users.destroy', $user->id)}}"  method="POST" class="float-left">
                                        @csrf @method('DELETE')
                                        <button type="submit" class="btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
                                    </form>
                                </th>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {{$users->links()}}
            </div>
        </div>
    </div>
@endsection